### ISSUE TITLE
 MVPリリース

### ISSUE THREAD

**Issue by shiranon** [shiranon/VRC_Avatar_Ranking_remix#55]
## 各種情報
サービスの概要とMVPで検証する事柄：
サービス名：rVRC
サービスURL：http://r-vrc.net/

### 運用リポジトリ
セキュリティや本番環境へのリリース、開発時の無関係なログを見せないようにするために、  
以下のリポジトリを運用リポジトリとして別途公開しようと思います。
https://github.com/shiranon/rVRC

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] AWS Lambdaでの自動データスクレイピング
- [x] 商品スキ数のデイリー・ウィークリー(トレンド)ランキング表示
- [x] ワード検索、絞り込み、ソート
- [x] お気に入り商品のフォルダ分け
- [x] Discordでのユーザー登録
- [ ] X bot (本リリースまでに作成)

## READMEレビュー時から変更した機能
 - DBaaSをAWS DynamoDBからSupabaseに変更
 - ストレージにCloudflare R2を採用
 - CMSを非採用

## サービスイメージがわかるようなスクリーンショット等
https://gyazo.com/621ba148f7cd37029065c314281b5782
https://gyazo.com/4b62663ceb60f32896c31197eb3483ca
https://gyazo.com/cb64af6188e22f8deac0845dadaf6105
https://gyazo.com/d3f0713c44a03751b64b800a7ca15180

**Comment by TakenakaEri** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

また、今回運用リポジトリを分けると言うことでしたが、エンジニアになるための就職活動を行うのであれば、リポジトリの公開は必須となります。普段よりどのように学習を行なっているのかや、コードの書き方などを企業様は見られますので、その点を踏まえてリポジトリを分けるのかどうかを検討してください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
